/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products */
        get: operations["products_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{gtin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product */
        get: operations["product_products__gtin__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BrandDetail */
        BrandDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Website */
            website: string;
        };
        /** BrandReference */
        BrandReference: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "brand";
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** CompanyOwnershipPoint */
        CompanyOwnershipPoint: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "company";
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Company Type
             * @enum {string}
             */
            company_type: "public" | "private" | "cooperative";
            /** Country */
            country: string;
        };
        /** CompanyReference */
        CompanyReference: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "company";
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "healthy";
        };
        /** OwnershipGroupPoint */
        OwnershipGroupPoint: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ownership_group";
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Country */
            country: string;
        };
        /** OwnershipGroupReference */
        OwnershipGroupReference: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ownership_group";
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** OwnershipRelationship */
        OwnershipRelationship: {
            /** Child */
            child: components["schemas"]["BrandReference"] | components["schemas"]["CompanyReference"] | components["schemas"]["OwnershipGroupReference"];
            /**
             * Relationship Type
             * @enum {string}
             */
            relationship_type: "owned_by" | "controlled_by_group" | "affiliated_with_group";
            /** Parent */
            parent: components["schemas"]["CompanyReference"] | components["schemas"]["OwnershipGroupReference"];
            /**
             * Verification Status
             * @enum {string}
             */
            verification_status: "verified" | "probable" | "unresolved";
            /** Confidence */
            confidence: number;
            /** Effective From */
            effective_from: string | null;
            /** Effective From Precision */
            effective_from_precision: ("year" | "month" | "day") | null;
            /** Effective Until */
            effective_until: string | null;
            /** Last Verified At */
            last_verified_at: string;
            /** Sources */
            sources: components["schemas"]["SupportingSource"][];
        };
        /** ProductBrand */
        ProductBrand: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ProductDetail */
        ProductDetail: {
            /** Id */
            id: string;
            /** Gtin */
            gtin: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Package Company Text */
            package_company_text: string;
        };
        /** ProductListResponse */
        ProductListResponse: {
            /** Products */
            products: components["schemas"]["ProductSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ProductOwnershipResponse */
        ProductOwnershipResponse: {
            product: components["schemas"]["ProductDetail"];
            brand: components["schemas"]["BrandDetail"];
            /** Ownership Chain */
            ownership_chain: components["schemas"]["OwnershipRelationship"][];
            /** Highest Verified Owner */
            highest_verified_owner: components["schemas"]["BrandReference"] | components["schemas"]["CompanyOwnershipPoint"] | components["schemas"]["OwnershipGroupPoint"];
            /** Chain Complete */
            chain_complete: boolean;
            /**
             * Overall Status
             * @enum {string}
             */
            overall_status: "verified" | "verified_with_gaps" | "cycle_detected";
            /**
             * Stop Reason
             * @enum {string}
             */
            stop_reason: "terminal_owner" | "research_gap" | "unresolved_relationship" | "multiple_verified_parents" | "cycle_detected";
            /** Research Gaps */
            research_gaps: components["schemas"]["ResearchGap"][];
        };
        /** ProductSummary */
        ProductSummary: {
            /** Id */
            id: string;
            /** Gtin */
            gtin: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            brand: components["schemas"]["ProductBrand"];
        };
        /** ResearchGap */
        ResearchGap: {
            /** Id */
            id: string;
            subject: components["schemas"]["ResearchGapSubject"];
            /** Issue Type */
            issue_type: string;
            /**
             * Status
             * @constant
             */
            status: "unresolved";
            /** Confidence */
            confidence: number;
            /** Explanation */
            explanation: string;
            /** Sources */
            sources: components["schemas"]["SupportingSource"][];
        };
        /** ResearchGapSubject */
        ResearchGapSubject: {
            /**
             * Type
             * @enum {string}
             */
            type: "brand" | "company" | "ownership_group";
            /** Id */
            id: string;
        };
        /** SupportingSource */
        SupportingSource: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Publisher */
            publisher: string;
            /** Source Type */
            source_type: string;
            /**
             * Support Type
             * @enum {string}
             */
            support_type: "primary" | "secondary";
            /** Published At */
            published_at: string | null;
            /** Retrieved At */
            retrieved_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    products_products_get: {
        parameters: {
            query?: {
                brand?: string | null;
                category?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_products__gtin__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gtin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOwnershipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
